/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectresto;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jose Witjaksono
 */
public class frmRekap extends javax.swing.JFrame {

    /**
     * Creates new form frmRekap
     */
    public frmRekap() {
        initComponents();
    kasir();
    setTanggal();
    setUndecorated(true);
    }
    
    String tanggal1="";
    String tanggal2="";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lbTanggal = new javax.swing.JLabel();
        lbSelamat = new javax.swing.JLabel();
        tfNama = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbData = new javax.swing.JTable();
        tfTotal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfHal = new javax.swing.JLabel();
        tfTanggal = new com.toedter.calendar.JDateChooser();
        bRekap = new javax.swing.JButton();
        tfTanggal1 = new com.toedter.calendar.JDateChooser();
        bTotal = new javax.swing.JButton();
        bInput = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bHias = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(null);

        lbTanggal.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        lbTanggal.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(lbTanggal);
        lbTanggal.setBounds(80, 50, 120, 31);

        lbSelamat.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        lbSelamat.setForeground(new java.awt.Color(255, 255, 255));
        lbSelamat.setText("Selamat Datang");
        jPanel3.add(lbSelamat);
        lbSelamat.setBounds(40, 10, 140, 31);

        tfNama.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        tfNama.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(tfNama);
        tfNama.setBounds(180, 10, 120, 31);

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(80, 80, 90, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(579, 0, 260, 120);

        jLabel4.setFont(new java.awt.Font("Bebas Neue", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("KANTIN smk TELKOM");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(100, 0, 470, 50);

        jLabel6.setFont(new java.awt.Font("SquareFont", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(100, 40, 370, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon("F:\\logo12.png")); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 0, 100, 120);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 840, 120);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jLabel1.setText("Tanggal Akhir");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(390, 40, 100, 31);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(null);

        tbData.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        tbData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Transaksi", "Tanggal", "Kasir", "Menu", "Jumlah", "Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbData);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 560, 330);

        tfTotal.setEditable(false);
        tfTotal.setText("0");
        jPanel4.add(tfTotal);
        tfTotal.setBounds(590, 40, 200, 29);

        jLabel8.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jLabel8.setText("Total Pemasukan");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(590, 10, 200, 31);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(10, 80, 820, 350);

        tfHal.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jPanel2.add(tfHal);
        tfHal.setBounds(120, 250, 90, 30);

        tfTanggal.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                tfTanggalHierarchyChanged(evt);
            }
        });
        tfTanggal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfTanggalKeyPressed(evt);
            }
        });
        jPanel2.add(tfTanggal);
        tfTanggal.setBounds(180, 10, 200, 30);

        bRekap.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        bRekap.setText("SEARCH");
        bRekap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRekapActionPerformed(evt);
            }
        });
        jPanel2.add(bRekap);
        bRekap.setBounds(580, 40, 120, 30);

        tfTanggal1.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                tfTanggal1HierarchyChanged(evt);
            }
        });
        tfTanggal1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfTanggal1KeyPressed(evt);
            }
        });
        jPanel2.add(tfTanggal1);
        tfTanggal1.setBounds(180, 40, 200, 30);

        bTotal.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        bTotal.setText("TOTAL");
        bTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTotalActionPerformed(evt);
            }
        });
        jPanel2.add(bTotal);
        bTotal.setBounds(580, 10, 120, 30);

        bInput.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        bInput.setText("INPUT ORDER");
        bInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInputActionPerformed(evt);
            }
        });
        jPanel2.add(bInput);
        bInput.setBounds(700, 10, 130, 30);

        jLabel2.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jLabel2.setText("Pilih Tanggal Transaksi");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 10, 180, 31);

        jLabel3.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jLabel3.setText("Tanggal Awal");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(390, 10, 100, 31);

        bHias.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        bHias.setEnabled(false);
        bHias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHiasActionPerformed(evt);
            }
        });
        jPanel2.add(bHias);
        bHias.setBounds(700, 40, 130, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 130, 840, 440);

        setSize(new java.awt.Dimension(860, 578));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDataMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbDataMouseClicked

    private void bInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInputActionPerformed
        // TODO add your handling code here:
            new frmMain(null).setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_bInputActionPerformed

    private void bRekapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRekapActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        String tanggal1 = dateFormat.format(tfTanggal.getDate());
        String tanggal2 = dateFormat.format(tfTanggal1.getDate());
        String kolom[] = {"ID_Transaksi","Tanggal","Kasir","Menu","Jumlah","Harga"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT id_transaksi,tanggal_transaksi,kasir,menu,jumlah,harga FROM tb_transaksi where tanggal_transaksi>'"+tanggal1+"' AND tanggal_transaksi<'"+tanggal2+"'";
        ResultSet rs = KoneksiDB.executeQuery(SQL);        
        try
        {
            while(rs.next())
            {
                String ID_Transaksi = rs.getString(1);
                String Tanggal = rs.getString(2);
                String Kasir = rs.getString(3);
                String Menu = "";
                   if("1".equals(rs.getString(4)))
                   {
                       Menu = "Indomie Rebus";
                   }
                   if("2".equals(rs.getString(4)))
                   {
                       Menu = "Telur Ceplok";
                   }
                   if("3".equals(rs.getString(4)))
                   {
                       Menu = "Es Teh";
                   }
                   if("4".equals(rs.getString(4)))
                   {
                       Menu = "Kopi";
                   }                   
                String Jumlah = rs.getString(5);
                String Harga = rs.getString(6);
                String data[] = {ID_Transaksi,Tanggal,Kasir,Menu,Jumlah,Harga};
                dtm.addRow(data);
                
            }
        }
        catch(SQLException ex)
        {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        tbData.setModel(dtm);
    }//GEN-LAST:event_bRekapActionPerformed

    private void tfTanggalHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_tfTanggalHierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTanggalHierarchyChanged

    private void tfTanggalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTanggalKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTanggalKeyPressed

    private void bTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTotalActionPerformed
        // TODO add your handling code here:
        int banyak = tbData.getRowCount();
        int hasil = 0;
        for (int i = 0; i < banyak; i++) {
            hasil += Integer.parseInt(tbData.getValueAt(i, 5).toString());
        }
        tfTotal.setText(String.valueOf(hasil));
    }//GEN-LAST:event_bTotalActionPerformed

    private void tfTanggal1HierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_tfTanggal1HierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTanggal1HierarchyChanged

    private void tfTanggal1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTanggal1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTanggal1KeyPressed

    private void bHiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bHiasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRekap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRekap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRekap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRekap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRekap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bHias;
    private javax.swing.JButton bInput;
    private javax.swing.JButton bRekap;
    private javax.swing.JButton bTotal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbSelamat;
    private javax.swing.JLabel lbTanggal;
    private javax.swing.JTable tbData;
    private javax.swing.JLabel tfHal;
    private javax.swing.JLabel tfNama;
    private com.toedter.calendar.JDateChooser tfTanggal;
    private com.toedter.calendar.JDateChooser tfTanggal1;
    private javax.swing.JTextField tfTotal;
    // End of variables declaration//GEN-END:variables
        private void kasir() {
        String SQL = "SELECT * FROM tb_akun";
        ResultSet result = KoneksiDB.executeQuery(SQL);
        try {
            while(result.next()){
                String namaKasir = result.getString(4);
                String usr = "Jose";
                tfNama.setText(usr);
                new frmMain(usr);
            }
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        public void setTanggal()
    {
        java.util.Date skrg = new java.util.Date();
        java.text.SimpleDateFormat kal = new
        java.text.SimpleDateFormat("dd-MM-yyyy");
        lbTanggal.setText(kal.format(skrg));
    }
}
